### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by facuquilmes123** [akgupta0777/YouTube-Downloader#4]
Hi Bro's. Thanks for that develop. I have a question.
What about server side in https://ytytd.herokuapp.com ?
Can u give me an example for that?
Thanks a lot !

**Comment by akgupta0777** [comment]
https://github.com/akgupta0777/YT-Downloader-Server

Check this out.
Thanks for appreciation.

**Comment by facuquilmes123** [comment]
Oh you are the best bro !!! Thank you very much

**Comment by akgupta0777** [comment]
Closing this issue. Thanks
